spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgresql
    hikari:
      schema: test_task_schema
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
    default-schema: test_task_schema